### ISSUE TITLE
PTZ Location returns '0' values

### ISSUE THREAD

**Issue by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [mictlanix/onvif#1]
I just wanted to post this here in case I forgot. So all of the tests passed without any issues except for the presets. It's successfully returning the preset names but not the p/t/z values. I'll do a better write up tonight with more info. I'm testing against dahua, canon, and amcrest cameras. 

Great work, this looks awesome

**Comment by ezavaleta** [comment]
I think your cameras don't fully support onvif presets, I have the same results for a Chinese cam (VStarcam C7824WIP) but presets works great for another cam (Siqura HSD626).
> Presets count: 1
> Preset: PresetToken_1 Name: P1 Pan: 0.9983335 Tilt: -0.8181818 Zoom: -2.941139E-05

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
It's possible, There's also a few different specs of Onvif I've noticed. 


However, if you try this I can get info on ptz presets from all those camera brand I found.

https://sourceforge.net/projects/onvifdm/


I'm gonna look through the code and see what was different on the implementation.
